version: '3.3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: Orange
  prometheus:
    image: prom/prometheus:v2.22.0
    command: "--config.file=/etc/prometheus/prometheus.yml --log.level=debug"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
